import WhishListWrapper from "../../../Wrappers/WhishListWrapper";

export const metadata = {
  title: "KG Grocery App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/KGlogo.png",
  },
};

export default function Wishlist() {
  return <WhishListWrapper />;
}
