import AdminDashboard from "./AdminDashboard";

export const metadata = {
  title: "KG Grocery App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/KGlogo.png",
  },
};
export default function page() {
  return (
    <div>
      <AdminDashboard />
    </div>
  );
}
