import OrderTrackingWrapper from "Wrappers/OrderTrackingWrapper";

export const metadata = {
  title: "KG Grocery App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/KGlogo.png",
  },
};
export default function OrderTracking() {
  return <OrderTrackingWrapper />;
}
