"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./providers/AuthProvider";
import { Provider } from "react-redux";
import { store } from "./Redux/services/store";
import Banner from "./_components/Banner";
import Footer from "./_components/Footer";
import DesktopHeader from "./_components/HeaderDesktop/DesktopHeader";
import MobileHeader from "./_components/HeaderPhone/MobileHeader.jsx";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "KG Grocery App",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/images/KGlogo.png",
//   },
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden`}>
        <Provider store={store}>
          <AuthProvider>
            <MobileHeader />
            <DesktopHeader />
            {children}
            <Banner />
            <Footer />
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
