import Navbar from "./_components/Navbar";
import HearoSeaction from "./_components/HearoSeaction/HearoSeaction";
import Catagory from "./_components/Catagory";
import Products from "./_components/Products";
import Banner from "./_components/Banner";
import Footer from "./_components/Footer";

export const metadata = {
  title: "KG Grocery App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/KGlogo.png",
  },
};


export default function Home() {
  return (
    <>
        <Navbar />
        <HearoSeaction />
        <Catagory />
        <Products />
        <Banner />
        <Footer />
      
    </>
  );
}
