import HearoSeaction from "./_components/HearoSeaction/HearoSeaction";
import Catagory from "./_components/Catagory";
import Products from "./_components/Products";

export const metadata = {
  title: "KG Grocery App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/KGlogo.png",
  },
};

export default function Home() {
  return (
    <>
      <HearoSeaction />
      <Catagory />
      <Products />
    </>
  );
}
