"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "../Redux/services/store";
import AuthProvider from "Providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "KG Grocery App",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/images/KGlogo.png",
//   },
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden bg-[--background-color] text-[--text-color]`}>
        <Provider store={store}>
          <AuthProvider>{children}</AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
