import Banner from "_components/Banner";
import Catagory from "_components/Catagory";
import DailyBestSells from "_components/Client/DailyBestSells/DailyBestSells";
import DealsOfTheDay from "_components/Client/DealsOfTheDay/DealsOfTheDay";
import FixedCards from "_components/Client/FixedCards/FixedCards";
import HearoSeaction from "_components/Client/HearoSeaction/HearoSeaction";
import ProductGrid from "_components/Client/ProductGrid/ProductGrid";
import Footer from "_components/Footer";
import DesktopHeader from "_components/HeaderDesktop/DesktopHeader";
import MobileHeader from "_components/HeaderPhone/MobileHeader";
import PhoneAd from "_components/HeaderPhone/PhoneAd";
import Products from "_components/Products";
import WelcomeModal from "_components/WelcomeModal/WelcomeModal";


export const metadata = {
  title: "KG Grocery App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/KGlogo.png",
  },
};

export default function Home() {
  return (
    <div className="overflow-x-hidden">
      <PhoneAd />
      <MobileHeader />
      <DesktopHeader />
      <HearoSeaction />
      <div className="px-5">
        <DealsOfTheDay />
        <Catagory />
        <Products />
        <FixedCards />
      </div>
      <DailyBestSells />
      <ProductGrid />
      <Banner />
      <Footer />
      <WelcomeModal />
    </div>
  );
}
