import Banner from "_components/Banner";
import Catagory from "_components/Catagory";
import DailyBestSells from "_components/Client/DailyBestSells/DailyBestSells";
import DealsOfTheDay from "_components/Client/DealsOfTheDay/DealsOfTheDay";
import FixedCards from "_components/Client/FixedCards/FixedCards";
import HearoSeaction from "_components/Client/HearoSeaction/HearoSeaction";
import Footer from "_components/Footer";
import DesktopHeader from "_components/HeaderDesktop/DesktopHeader";
import MobileHeader from "_components/HeaderPhone/MobileHeader";
import Products from "_components/Products";

export const metadata = {
  title: "KG Grocery App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/KGlogo.png",
  },
};

export default function Home() {
  return (
    <>
      <MobileHeader />
      <DesktopHeader />
      <HearoSeaction />
      <div className="px-5">
        <DealsOfTheDay />
        <Catagory />
        <Products />
        <FixedCards />
        <DailyBestSells />
      </div>
      <Banner />
      <Footer />
    </>
  );
}
